# Generated by Django 4.1.4 on 2022-12-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprroved'),
        ),
    ]
